"""Crush adapter tests: CRUSH.md rules + crush.json MCP keyed-merge, plus
skip-absent. Crush isn't installed here, so everything runs in temp dirs.
"""
import json
import os
import tempfile
import unittest
from pathlib import Path

from agentconfig.core import run

REPO = Path(__file__).resolve().parent.parent

SEED = {"$schema": "x", "models": {"large": "vllm"}, "mcp": {"theirs": {"type": "stdio"}}}


def _run(base: Path, *, crush_dir: Path):
    return run(REPO, env={
        **os.environ,
        "CLAUDE_DIR": str(base / ".claude"),
        "CODEX_DIR": str(base / ".codex-absent"),
        "OPENCODE_DIR": str(base / ".opencode-absent"),
        "CRUSH_DIR": str(crush_dir),
        "AGENT_CONFIG_STATE": str(base / "state.json"),
    })


class CrushTest(unittest.TestCase):
    def test_rules_and_mcp_preserve_config(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            crush = base / "crush"
            crush.mkdir()
            (crush / "crush.json").write_text(json.dumps(SEED))
            _run(base, crush_dir=crush)

            self.assertIn("generated by agent-config", (crush / "CRUSH.md").read_text())
            data = json.loads((crush / "crush.json").read_text())
            self.assertEqual(data["models"], {"large": "vllm"})   # preserved
            self.assertIn("theirs", data["mcp"])                  # their server kept
            self.assertIn("transcribemcp", data["mcp"])           # ours added
            self.assertEqual(data["mcp"]["transcribemcp"]["type"], "stdio")
            self.assertTrue(data["mcp"]["transcribemcp"]["command"].endswith("transcribemcp-run"))
            # permissions/subagents/hooks are gaps — not emitted
            self.assertNotIn("permissions", data)

    def test_skipped_when_absent(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            crush = base / ".crush-not-created"
            res = _run(base, crush_dir=crush)
            self.assertFalse(crush.exists())
            self.assertEqual(res.failures, [])


if __name__ == "__main__":
    unittest.main()
