"""Codex adapter tests: AGENTS.md rules rendering + skip-absent.

All harness dirs point into temp; the real ~/.codex is never touched.
"""
import os
import tempfile
import unittest
from pathlib import Path

from agentconfig.core import run

REPO = Path(__file__).resolve().parent.parent


def _run(base: Path, *, codex_dir: Path):
    return run(REPO, env={
        **os.environ,
        "CLAUDE_DIR": str(base / ".claude"),
        "CODEX_DIR": str(codex_dir),
        "AGENT_CONFIG_STATE": str(base / "state.json"),
    })


class CodexRulesTest(unittest.TestCase):
    def test_agents_md_rendered_when_present(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            codex = base / ".codex"
            codex.mkdir()
            _run(base, codex_dir=codex)

            text = (codex / "AGENTS.md").read_text()
            self.assertIn("generated by agent-config", text)
            self.assertNotIn("@./", text)  # flattened, not @import lines
            # every rule file's content is embedded verbatim
            for name in ("userprofile.md", "style.md", "communication.md", "engineering.md"):
                body = (REPO / name).read_text().strip()
                self.assertIn(body[:120], text, name)

    def test_skipped_when_absent(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            codex = base / ".codex-not-created"  # does not exist → skip-absent
            res = _run(base, codex_dir=codex)
            self.assertFalse(codex.exists())  # generator did not create it
            # the Claude side still rendered fine
            self.assertEqual(res.failures, [])


SEED_CONFIG = '''model = "gpt-5.4"
personality = "pragmatic"
notify = ["x", "turn-ended"]

[projects."/Users/charlie/projects/orbitron"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
'''


class CodexSkillsTest(unittest.TestCase):
    def test_skills_copied_and_registered_preserving_config(self):
        import tomllib
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            codex = base / ".codex"
            codex.mkdir()
            (codex / "config.toml").write_text(SEED_CONFIG)
            _run(base, codex_dir=codex)

            # portable skills copied into ~/.codex/skills
            self.assertTrue((codex / "skills" / "bug-hunter" / "SKILL.md").is_file())

            text = (codex / "config.toml").read_text()
            # co-managed content preserved verbatim
            self.assertIn('personality = "pragmatic"', text)
            self.assertIn('[projects."/Users/charlie/projects/orbitron"]', text)
            self.assertIn('[notice.model_migrations]', text)
            # valid TOML; our keys present, theirs untouched
            data = tomllib.loads(text)
            self.assertEqual(data["model"], "gpt-5.4")
            self.assertEqual(data["projects"]["/Users/charlie/projects/orbitron"]["trust_level"], "trusted")
            entries = data["skills"]["config"]
            self.assertGreaterEqual(len(entries), 1)
            self.assertTrue(all(e["enabled"] for e in entries))
            self.assertTrue(all("/.codex/skills/" in e["path"] for e in entries))

    def test_managed_block_idempotent_single_block(self):
        import tomllib
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            codex = base / ".codex"
            codex.mkdir()
            (codex / "config.toml").write_text(SEED_CONFIG)
            _run(base, codex_dir=codex)
            first = (codex / "config.toml").read_text()
            _run(base, codex_dir=codex)
            second = (codex / "config.toml").read_text()
            self.assertEqual(first, second)                      # idempotent
            self.assertEqual(second.count(">>> agent-config managed"), 1)  # not duplicated
            tomllib.loads(second)                                # still valid TOML


class CodexMcpTest(unittest.TestCase):
    def test_mcp_registered_alongside_skills_one_block(self):
        import tomllib
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            codex = base / ".codex"
            codex.mkdir()
            _run(base, codex_dir=codex)

            text = (codex / "config.toml").read_text()
            self.assertEqual(text.count(">>> agent-config managed"), 1)  # one block
            data = tomllib.loads(text)
            servers = data.get("mcp_servers", {})
            self.assertIn("transcribemcp", servers)  # manifest targets it at codex
            self.assertTrue(servers["transcribemcp"]["command"].endswith("transcribemcp-run"))
            self.assertNotIn("~", servers["transcribemcp"]["command"])  # expanded
            self.assertGreaterEqual(len(data["skills"]["config"]), 1)  # coexists with skills


if __name__ == "__main__":
    unittest.main()
