"""Codex adapter tests: AGENTS.md rules rendering + skip-absent.

All harness dirs point into temp; the real ~/.codex is never touched.
"""
import os
import tempfile
import unittest
from pathlib import Path

from agentconfig.core import run

REPO = Path(__file__).resolve().parent.parent


def _run(base: Path, *, codex_dir: Path):
    return run(REPO, env={
        **os.environ,
        "CLAUDE_DIR": str(base / ".claude"),
        "CODEX_DIR": str(codex_dir),
        "AGENT_CONFIG_STATE": str(base / "state.json"),
    })


class CodexRulesTest(unittest.TestCase):
    def test_agents_md_rendered_when_present(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            codex = base / ".codex"
            codex.mkdir()
            _run(base, codex_dir=codex)

            text = (codex / "AGENTS.md").read_text()
            self.assertIn("generated by agent-config", text)
            self.assertNotIn("@./", text)  # flattened, not @import lines
            # every rule file's content is embedded verbatim
            for name in ("userprofile.md", "style.md", "communication.md", "engineering.md"):
                body = (REPO / name).read_text().strip()
                self.assertIn(body[:120], text, name)

    def test_skipped_when_absent(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            codex = base / ".codex-not-created"  # does not exist → skip-absent
            res = _run(base, codex_dir=codex)
            self.assertFalse(codex.exists())  # generator did not create it
            # the Claude side still rendered fine
            self.assertEqual(res.failures, [])


if __name__ == "__main__":
    unittest.main()
