"""pi adapter tests: AGENTS.md rules (pi's only ported asset) + skip-absent.
Everything in temp dirs; the real ~/.pi/agent is never touched.
"""
import os
import tempfile
import unittest
from pathlib import Path

from agentconfig.core import run

REPO = Path(__file__).resolve().parent.parent


def _run(base: Path, *, pi_dir: Path):
    return run(REPO, env={
        **os.environ,
        "CLAUDE_DIR": str(base / ".claude"),
        "CODEX_DIR": str(base / ".codex-absent"),
        "OPENCODE_DIR": str(base / ".opencode-absent"),
        "CRUSH_DIR": str(base / ".crush-absent"),
        "PI_DIR": str(pi_dir),
        "AGENT_CONFIG_STATE": str(base / "state.json"),
    })


class PiTest(unittest.TestCase):
    def test_rules_rendered(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            pi = base / "pi-agent"
            pi.mkdir()
            _run(base, pi_dir=pi)
            text = (pi / "AGENTS.md").read_text()
            self.assertIn("generated by agent-config", text)
            self.assertIn((REPO / "userprofile.md").read_text().strip()[:80], text)

    def test_skipped_when_absent(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            pi = base / "pi-not-created"
            res = _run(base, pi_dir=pi)
            self.assertFalse(pi.exists())
            self.assertEqual(res.failures, [])


if __name__ == "__main__":
    unittest.main()
