"""opencode adapter tests: AGENTS.md rules + MCP keyed-merge that preserves the
user's existing opencode.json content. All dirs point into temp.
"""
import json
import os
import tempfile
import unittest
from pathlib import Path

from agentconfig.core import run

REPO = Path(__file__).resolve().parent.parent

# Mimics a real opencode.json: a provider + model + existing mcp servers.
SEED = {
    "$schema": "https://opencode.ai/config.json",
    "provider": {"vllm": {"options": {"apiKey": "sk-local"}}},
    "model": "vllm/nemotron-3-super",
    "mcp": {
        "office-word": {"type": "local", "command": ["uv", "run", "x"], "enabled": True},
    },
}


def _run(base: Path, *, oc_dir: Path):
    return run(REPO, env={
        **os.environ,
        "CLAUDE_DIR": str(base / ".claude"),
        "CODEX_DIR": str(base / ".codex-absent"),
        "OPENCODE_DIR": str(oc_dir),
        "AGENT_CONFIG_STATE": str(base / "state.json"),
    })


class OpencodeTest(unittest.TestCase):
    def test_rules_and_mcp_merge_preserve_user_config(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            oc = base / "opencode"
            oc.mkdir()
            (oc / "opencode.json").write_text(json.dumps(SEED, indent=2))
            _run(base, oc_dir=oc)

            # rules
            self.assertIn("generated by agent-config", (oc / "AGENTS.md").read_text())

            data = json.loads((oc / "opencode.json").read_text())
            # user content preserved
            self.assertEqual(data["model"], "vllm/nemotron-3-super")
            self.assertEqual(data["provider"]["vllm"]["options"]["apiKey"], "sk-local")
            self.assertIn("office-word", data["mcp"])          # their server kept
            # our server added (manifest targets transcribemcp at opencode)
            self.assertIn("transcribemcp", data["mcp"])
            self.assertEqual(data["mcp"]["transcribemcp"]["type"], "local")
            self.assertTrue(data["mcp"]["transcribemcp"]["command"][0].endswith("transcribemcp-run"))

    def test_permissions_bash_floor_ported(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            oc = base / "opencode"
            oc.mkdir()
            (oc / "opencode.json").write_text(json.dumps(SEED, indent=2))
            _run(base, oc_dir=oc)

            data = json.loads((oc / "opencode.json").read_text())
            bash = data["permission"]["bash"]
            self.assertEqual(bash["*"], "ask")                       # default
            self.assertEqual(bash.get("git push --force*"), "deny")  # deny floor
            self.assertEqual(bash.get("rm -rf /*"), "deny")
            self.assertEqual(bash.get("git status*"), "allow")       # allow-list
            self.assertEqual(data["model"], "vllm/nemotron-3-super")  # not clobbered

    def test_idempotent(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            oc = base / "opencode"
            oc.mkdir()
            (oc / "opencode.json").write_text(json.dumps(SEED, indent=2))
            _run(base, oc_dir=oc)
            first = (oc / "opencode.json").read_text()
            _run(base, oc_dir=oc)
            self.assertEqual(first, (oc / "opencode.json").read_text())

    def test_jsonc_with_comments_not_clobbered(self):
        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            oc = base / "opencode"
            oc.mkdir()
            jsonc = '{\n  // a real comment\n  "model": "x"\n}\n'
            (oc / "opencode.json").write_text(jsonc)
            res = _run(base, oc_dir=oc)
            # refused to merge (can't parse) → file untouched, failure reported
            self.assertEqual((oc / "opencode.json").read_text(), jsonc)
            self.assertTrue(any("opencode" in a for a, _ in res.failures))


if __name__ == "__main__":
    unittest.main()
