"""Render the neutral rule files into a flat AGENTS.md.

Codex, opencode, Crush, and pi all read AGENTS.md but none resolve the
`@import`s a Claude CLAUDE.md uses — so the four topic files are concatenated
into one self-describing file. Shared by every non-Claude adapter.
"""
from __future__ import annotations

from pathlib import Path

from .manifest import Manifest

_MARKER = "<!-- generated by agent-config — edits are overwritten; regenerate with ./install.sh -->"


def render_agents_md(manifest: Manifest, repo_root) -> str:
    repo_root = Path(repo_root)
    parts = [_MARKER, f"<!-- Source: {', '.join(manifest.rule_files)} -->"]
    for name in manifest.rule_files:
        parts.append("")  # blank line between sections
        parts.append((repo_root / name).read_text().rstrip("\n"))
    return "\n".join(parts) + "\n"
